Add minder OSPS minder profiles and first rules
ossf/security-baseline pull request #107
Opened 2024-12-11 02:46 UTC by puerco

This pull request adds the three skeletons for minder profiles for each level of the baseline, the are written to be applied incrementally as a project matures:

- `osps-baseline-level1.yaml` → Level 1
- `osps-baseline-level2.yaml` → Level 2
- `osps-baseline-level3.yaml` → Level 3

This PR is intended to add the initial template for the profiles, however I've added a few rules to ensure it works now.

Signed-off-by: Adolfo García Veytia (puerco) <puerco@stacklok.com>

2024-12-16 18:18 UTC, SecurityCRob approved these changes

2024-12-20 18:56 UTC, david-a-wheeler commented on resources/minder/README.md
> +profiles that any project can use to monitor its compliance with the
```suggestion
profiles that any project can use to experimentally monitor its compliance with the 
```

2024-12-20 18:57 UTC, david-a-wheeler commented on resources/minder/README.md
> +Open Source Project Security Baseline.
```suggestion
Open Source Project Security Baseline.
Note that the baseline is still in development, as are these profiles.
```

2024-12-20 18:59 UTC, david-a-wheeler commented
Since we're still working on some things, I think it's really important to be up-front that this is early-stage work. I *applaud* early-stage work, don't get me wrong, I just don't want people to grab this & think it's all done now. :-).

I made a few tweaks above. As long as we mark things like that (it could be noted differently), so people understand its early nature, then wonderful!

2024-12-20 21:12 UTC, eddie-knight requested changes
Agree with @david-a-wheeler, and I think we should stabilize this before merging it in

2024-12-26 21:41 UTC, puerco commented
Thanks for the review @david-a-wheeler, I also agree not to merge it until done. I'll close it as I won't be working on it anymore.

2024-12-26 21:41 UTC, closed without merging