shortened objective statement for workflow permissions
ossf/security-baseline pull request #52
Opened 2024-11-08 18:31 UTC by eddie-knight

2024-11-08 20:56 UTC, david-a-wheeler commented
This mixes 2 different issues. I'll create a new PR for *ONLY* shortening the objective statement.

2024-11-08 20:58 UTC, david-a-wheeler commented
See https://github.com/ossf/security-baseline/pull/61 instead.

2024-11-08 21:19 UTC, david-a-wheeler requested changes
See #61  instead.

2024-11-11 14:36 UTC, SecurityCRob approved these changes

2024-11-11 15:38 UTC, closed without merging